// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for automating responses to common customer queries, focusing on renewals and upsells.
 *
 * - automateCustomerQueryResponses -  A function that automates responses to customer queries.
 * - AutomateCustomerQueryResponsesInput - The input type for the automateCustomerQueryResponses function.
 * - AutomateCustomerQueryResponsesOutput - The output type for the automateCustomerQueryResponses function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AutomateCustomerQueryResponsesInputSchema = z.object({
  customerQuery: z.string().describe('The customer query to respond to.'),
  customerName: z.string().describe('The name of the customer.'),
  productDetails: z.string().describe('Details about the product the customer is asking about.'),
  renewalDate: z.string().describe('The renewal date of the customer product, if applicable.'),
});

export type AutomateCustomerQueryResponsesInput = z.infer<typeof AutomateCustomerQueryResponsesInputSchema>;

const AutomateCustomerQueryResponsesOutputSchema = z.object({
  response: z.string().describe('The automated response to the customer query.'),
});

export type AutomateCustomerQueryResponsesOutput = z.infer<typeof AutomateCustomerQueryResponsesOutputSchema>;

export async function automateCustomerQueryResponses(input: AutomateCustomerQueryResponsesInput): Promise<AutomateCustomerQueryResponsesOutput> {
  return automateCustomerQueryResponsesFlow(input);
}

const automateCustomerQueryResponsesPrompt = ai.definePrompt({
  name: 'automateCustomerQueryResponsesPrompt',
  input: {schema: AutomateCustomerQueryResponsesInputSchema},
  output: {schema: AutomateCustomerQueryResponsesOutputSchema},
  prompt: `You are an AI assistant helping GroMo partners respond to customer queries.

  Customer Name: {{customerName}}
  Product Details: {{productDetails}}
  Renewal Date: {{renewalDate}}

  Respond to the following customer query:
  {{customerQuery}}

  Your response should be professional and helpful. If the query is related to a renewal, provide information about the renewal process. If the query is related to an upsell opportunity, suggest relevant upsells based on the product details.
  If renewal date is provided, remind the customer about it and provide steps for renewal.
  `,
});

const automateCustomerQueryResponsesFlow = ai.defineFlow(
  {
    name: 'automateCustomerQueryResponsesFlow',
    inputSchema: AutomateCustomerQueryResponsesInputSchema,
    outputSchema: AutomateCustomerQueryResponsesOutputSchema,
  },
  async input => {
    const {output} = await automateCustomerQueryResponsesPrompt(input);
    return output!;
  }
);
